# Generated by Django 5.0.1 on 2024-01-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Имя файла')),
                ('upload_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления файла')),
            ],
        ),
    ]
